services:
  - name: backup-db
    type: cron
    schedule: "0 3 * * *"
    region: ohio
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: test-db
          property: connectionString
      - key: AWS_REGION
        sync: false # pick the region closest to your database
      - key: S3_BUCKET_NAME
        sync: false # this needs to be globally unique
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false

databases:
  - name: test-db
    region: ohio
